In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np

file_path = "/content/drive/MyDrive/Colab Notebooks/KMC_student_dataset.xlsx"
df = pd.read_excel(file_path)

print(df)

    Study Hours  Sleep Hours  Attendance Percentage  Exercise Hours   SSC GPA  \
0             7            7                     63               4  4.134026   
1             4            7                     66               4  4.370527   
2             8            4                     85               1  3.817880   
3             5            6                     99               6  4.778903   
4             7            8                     89               4  3.953231   
5             3            6                     53               1  4.744879   
6             7            8                     51               0  4.550116   
7             8            4                     55               3  3.348352   
8             5            5                     91               3  2.286230   
9             4            7                     53               3  3.112455   
10            8            4                     78               4  4.006524   
11            8            7

In [ ]:
data_array = df.to_numpy()
data_array=data_array.astype(float)
print(data_array)

[[ 7.          7.         63.          4.          4.13402586  2.60515761]
 [ 4.          7.         66.          4.          4.37052662  4.68729079]
 [ 8.          4.         85.          1.          3.81787992  3.42611067]
 [ 5.          6.         99.          6.          4.77890264  3.68982672]
 [ 7.          8.         89.          4.          3.95323108  4.08654826]
 [ 3.          6.         53.          1.          4.74487903  2.41799436]
 [ 7.          8.         51.          0.          4.55011573  3.81325214]
 [ 8.          4.         55.          3.          3.34835202  3.61952327]
 [ 5.          5.         91.          3.          2.28623035  2.60918367]
 [ 4.          7.         53.          3.          3.11245476  4.82856071]
 [ 8.          4.         78.          4.          4.00652376  3.7965964 ]
 [ 8.          7.         67.          0.          3.99776707  4.0843548 ]
 [ 3.          9.         75.          4.          3.77389336  4.64140352]
 [ 6.          5.        

In [ ]:
normalized_data=np.zeros_like(data_array)
noOfRows = normalized_data.shape[0]
noOfColumns = normalized_data.shape[1]

for i in range(noOfColumns):
    xmin = np.min(data_array[:,i])
    xmax = np.max(data_array[:,i])
    normalized_data[:,i] = (data_array[:,i] - xmin) / (xmax-xmin)
print(normalized_data)

[[0.75       0.6        0.25       0.66666667 0.72041646 0.11491476]
 [0.375      0.6        0.3125     0.66666667 0.80506738 0.94376372]
 [0.875      0.         0.70833333 0.16666667 0.60725807 0.44171714]
 [0.5        0.4        1.         1.         0.95123777 0.54669639]
 [0.75       0.8        0.79166667 0.66666667 0.65570442 0.70462204]
 [0.25       0.4        0.04166667 0.16666667 0.93905967 0.04040941]
 [0.75       0.8        0.         0.         0.86934787 0.59582919]
 [0.875      0.         0.08333333 0.5        0.43919953 0.51871022]
 [0.5        0.2        0.83333333 0.5        0.05903339 0.11651744]
 [0.375      0.6        0.04166667 0.5        0.35476462 1.        ]
 [0.875      0.         0.5625     0.66666667 0.67477952 0.58919893]
 [0.875      0.6        0.33333333 0.         0.67164523 0.70374888]
 [0.25       1.         0.5        0.66666667 0.59151392 0.92549706]
 [0.625      0.2        0.875      1.         0.25157695 0.61963817]
 [0.5        0.2        0.66666667

In [ ]:
k=3
noOfPoints = normalized_data.shape[0]
random_points = np.random.choice(noOfPoints, k, replace=False)

centroids = normalized_data[random_points]
print(centroids)

distances = np.zeros(shape=(noOfRows,k))
for i in range(k):
    distances[:,i] = np.sum(abs(normalized_data-centroids[i]),axis=1)

print(distances)

clusters = np.argmin(distances,axis = 1)
print(clusters)

new_clusters = np.zeros_like(clusters)

while True:
  new_centroids = np.zeros_like(centroids)
  print(new_centroids)
  for i in range(k):
    points = normalized_data[i==clusters]
    new_centroids[i] = points.mean(axis=0)

  print(new_centroids)

  for i in range(k):
    distances[:,i] = np.sum(abs(normalized_data - new_centroids[i]), axis = 1)

  print(distances)

  new_clusters = np.argmin(distances,axis = 1)
  print(new_clusters)

  if(np.array_equal(clusters, new_clusters)):
    break

  clusters = new_clusters

for i in range(k):
  points = normalized_data[i  == clusters]
  print("Cluster - " + str(i+1) + " : ")
  print(points)

[[0.         0.8        0.4375     0.33333333 0.07565646 0.95697769]
 [0.         0.6        0.27083333 0.5        0.23154699 0.26135825]
 [0.5        0.4        1.         1.         0.95123777 0.54669639]]
[[2.95765627 1.57281296 2.19593628]
 [1.77595824 1.8392592  1.88907105]
 [3.15936216 2.80190331 2.34895895]
 [3.41502928 2.93419559 0.        ]
 [2.26990362 2.50492123 1.64512566]
 [2.9924715  1.94096152 2.56013175]
 [2.67567325 2.69310516 2.7810227 ]
 [2.99764388 2.12750452 2.73169107]
 [2.51958332 1.7798544  2.18904999]
 [1.45963047 1.46602605 2.8331101 ]
 [3.10023516 2.70440654 1.86479412]
 [2.36171759 2.31998887 2.67831169]
 [1.39317143 2.06993908 2.42185785]
 [2.84242668 2.50747655 1.2226026 ]
 [2.87599271 1.82448273 1.57828876]
 [2.77825467 1.72674469 3.73850073]
 [3.54126487 3.1388178  2.04290225]
 [3.09374426 2.10890095 1.76991027]
 [2.46646738 1.96842306 2.36577253]
 [1.71661375 2.3765629  2.3650822 ]
 [1.38484331 0.         2.93419559]
 [2.81698412 1.74392187 2.67811746]
