In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataPath = "/content/drive/MyDrive/Colab Notebooks/Bus_Fare_Dataset.csv"
testDataPath = "/content/drive/MyDrive/Colab Notebooks/Test_Bus_Fare_Dataset.csv"

In [ ]:
dataFrame = pd.read_csv(dataPath)
testDataFrame = pd.read_csv(testDataPath)

print(dataFrame)
print(testDataFrame)

    Distance (km) Air Conditioned Television   Food Service    Bus Fare
0             307             Yes        Yes      Available  Affordable
1             491             Yes        Yes  Not Available  Affordable
2             327              No        Yes      Available     Premium
3             285             Yes        Yes      Available     Premium
4             400              No        Yes  Not Available  Affordable
5             412              No         No      Available     Premium
6             393             Yes        Yes  Not Available     Premium
7              86              No         No  Not Available      Budget
8             465              No         No  Not Available      Luxury
9             349              No        Yes  Not Available      Budget
10            417             Yes        Yes      Available     Premium
11            448              No         No      Available      Budget
12            238             Yes        Yes      Available     

In [ ]:
dataSet = dataFrame.to_numpy()
testDataSet = testDataFrame.to_numpy()

In [ ]:
dataSet[np.where(dataSet=='Yes')] = 1
dataSet[np.where(dataSet=='No')] = 0
dataSet[np.where(dataSet=='Available')] = 1
dataSet[np.where(dataSet=='Not Available')] = 1
dataSet[np.where(dataSet=='Affordable')] = 0
dataSet[np.where(dataSet=='Budget')] = 1
dataSet[np.where(dataSet=='Premium')] = 2
dataSet[np.where(dataSet=='Luxury')] = 3

print(dataSet)


testDataSet[np.where(testDataSet=='Yes')] = 1
testDataSet[np.where(testDataSet=='No')] = 0
testDataSet[np.where(testDataSet=='Available')] = 1
testDataSet[np.where(testDataSet=='Not Available')] = 1
testDataSet[np.where(testDataSet=='Affordable')] = 0
testDataSet[np.where(testDataSet=='Budget')] = 1
testDataSet[np.where(testDataSet=='Premium')] = 2
testDataSet[np.where(testDataSet=='Luxury')] = 3

print(testDataSet)

[[307 1 1 1 0]
 [491 1 1 1 0]
 [327 0 1 1 2]
 [285 1 1 1 2]
 [400 0 1 1 0]
 [412 0 0 1 2]
 [393 1 1 1 2]
 [86 0 0 1 1]
 [465 0 0 1 3]
 [349 0 1 1 1]
 [417 1 1 1 2]
 [448 0 0 1 1]
 [238 1 1 1 2]
 [370 1 1 1 1]
 [367 1 1 1 3]
 [63 0 0 1 1]
 [115 1 0 1 3]
 [214 0 0 1 3]
 [431 0 1 1 3]
 [302 1 1 1 3]
 [433 0 0 1 3]
 [166 0 0 1 1]
 [111 0 0 1 2]
 [408 1 1 1 1]
 [346 1 0 1 0]
 [370 0 1 1 2]
 [442 0 1 1 2]
 [358 0 0 1 2]
 [54 0 0 1 3]
 [432 0 1 1 2]
 [374 1 0 1 0]
 [472 0 0 1 0]
 [55 0 0 1 1]
 [61 0 1 1 1]
 [450 1 1 1 1]
 [74 0 1 1 0]
 [336 1 1 1 3]
 [55 1 0 1 3]
 [347 0 1 1 2]
 [452 1 1 1 0]
 [107 1 0 1 0]
 [169 1 1 1 2]
 [280 1 0 1 3]
 [181 1 1 1 3]
 [294 1 0 1 2]
 [382 0 0 1 3]
 [330 0 0 1 1]
 [404 0 0 1 1]
 [365 0 0 1 1]
 [102 1 1 1 2]]
[[204 1 0 1 3]
 [454 1 1 1 0]
 [62 0 1 1 3]
 [440 0 1 1 0]
 [444 1 0 1 0]
 [144 1 1 1 0]
 [490 0 1 1 0]
 [373 0 1 1 3]
 [200 1 0 1 0]
 [413 1 1 1 1]]


In [ ]:
def eucledianDistance(x1, x2):
    distance = 0
    for i in range(len(x1)):
        distance += (x1[i] - x2[i]) ** 2
    return distance ** 0.5

def predict(x_train, y_train, x_test, k=3):
    distances = []
    for i in range(len(x_train)):
        d = eucledianDistance(x_train[i], x_test)
        distances.append(d)

    sorted_distances = np.argsort(distances)[:k]

    poll = dict()
    poll[0] = 0  # Label 0
    poll[1] = 0  # Label 1
    poll[2] = 0  # Label 2
    poll[3] = 0  # Label 3

    for i in sorted_distances:
        label = y_train[i]
        poll[label] += 1

    return max(poll, key=poll.get)


x_train = dataSet[:, 0:4]
y_train = dataSet[:, 4]

x_test = testDataSet[:, 0:4]
y_test = testDataSet[:, 4]

correct_predictions = 0
correctly_predicted_rows = []

for i in range(len(x_test)):
    predicted_label = predict(x_train, y_train, x_test[i], k=3)
    actual_label = y_test[i]

    if predicted_label == actual_label:
        correct_predictions += 1
        correctly_predicted_rows.append(np.concatenate((x_test[i], [actual_label])))

print(f"Number of correctly predicted rows: {correct_predictions}")
print("Correctly predicted rows:")
for row in correctly_predicted_rows:
    print(row)

Number of correctly predicted rows: 2
Correctly predicted rows:
[204 1 0 1 3]
[490 0 1 1 0]
